# -*- coding: utf-8 -*-
"""Willkommen bei Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install plotly ipywidgets -q

import pandas as pd
import numpy as np
import plotly.express as px

from ipywidgets import interact, widgets

from google.colab import files

uploaded = files.upload()

import pandas as pd

filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)

df.head()

import pandas as pd

df = pd.read_csv(
    "oecd_data.csv"
)

df.head()

df.columns.tolist()

[col for col in df.columns if "flow" in col.lower() or "amount" in col.lower()]

[col for col in df.columns if "sector" in col.lower()]

# Nur Commitments behalten

print(df["FLOW_TYPE"].unique())
print(df["Flow type"].unique())

allowed_modalities = [
    "A02",
    "B01",
    "B03",
    "B031",
    "B032",
    "B033",
    "B034",
    "B04",
    "C01",
    "D01",
    "D02",
    "E01"
]

df = df[
    df["MODALITY"]
    .astype(str)
    .str[:3]
    .isin(allowed_modalities)
]

print("Nach Modality Filter:", len(df))

[col for col in df.columns if "sector" in col.lower()]

excluded_sectors = [
    "72010",
    "72040",
    "73010"
]

df = df[
    ~df["SECTOR"]
    .astype(str)
    .isin(excluded_sectors)
]

print("Nach Sector Ausschluss:", len(df))

# 1. Nur Commitments
df = df[
    df["FLOW_TYPE"] == "C"
]


# 2. Nur gewünschte Modalities

allowed_modalities = [
    "A02",
    "B01",
    "B03",
    "B031",
    "B032",
    "B033",
    "B034",
    "B04",
    "C01",
    "D01",
    "D02",
    "E01"
]

df = df[
    df["MODALITY"]
    .astype(str)
    .str[:3]
    .isin(allowed_modalities)
]


# 3. Sektoren ausschließen

excluded_sectors = [
    "72010",
    "72040",
    "73010"
]

df = df[
    ~df["SECTOR"]
    .astype(str)
    .isin(excluded_sectors)
]


print("Verbleibende Datensätze:", len(df))

[col for col in df.columns if "recipient" in col.lower()]

[col for col in df.columns if "donor" in col.lower()]

import pandas as pd
import plotly.express as px
from ipywidgets import interact, widgets


# Kopie erstellen
data = df.copy()


# -----------------------------
# 1. Nur Commitments
# -----------------------------

print(data["FLOW_TYPE"].unique())

data = data[
    data["FLOW_TYPE"].astype(str).str.upper().isin(
        ["C", "COMMITMENT"]
    )
]


# -----------------------------
# 2. Nur erlaubte Modalities
# -----------------------------

allowed_modalities = [
    "A02",
    "B01",
    "B03",
    "B031",
    "B032",
    "B033",
    "B034",
    "B04",
    "C01",
    "D01",
    "D02",
    "E01"
]

data = data[
    data["MODALITY"]
    .astype(str)
    .str[:3]
    .isin(allowed_modalities)
]


# -----------------------------
# 3. Sektoren ausschließen
# -----------------------------

excluded_sectors = [
    "72010",
    "72040",
    "73010"
]

data = data[
    ~data["SECTOR"]
    .astype(str)
    .isin(excluded_sectors)
]


print("Verbleibende CRS-Einträge:", len(data))

def disability_category(value):

    if pd.isna(value) or value == "":
        return "Not scored"

    try:
        value = int(value)
    except:
        return "Not scored"

    if value == 0:
        return "Scored - not targeted"

    if value in [1, 2]:
        return "Targeted"

    return "Not scored"


data["Disability Category"] = (
    data["DISABILITY"]
    .apply(disability_category)
)


data["Disability Category"].value_counts()

recipient_options = (
    ["All"] +
    sorted(data["Recipient"].dropna().unique().tolist())
)

donor_options = (
    ["All"] +
    sorted(data["Donor"].dropna().unique().tolist())
)

sector_options = (
    ["All"] +
    sorted(data["Sector"].dropna().unique().tolist())
)

def create_dashboard(
    Recipient="All",
    Donor="All",
    Sector="All"
):

    filtered = data.copy()


    if Recipient != "All":
        filtered = filtered[
            filtered["Recipient"] == Recipient
        ]


    if Donor != "All":
        filtered = filtered[
            filtered["Donor"] == Donor
        ]


    if Sector != "All":
        filtered = filtered[
            filtered["Sector"] == Sector
        ]


    result = (
        filtered["Disability Category"]
        .value_counts()
        .reset_index()
    )


    result.columns = [
        "Category",
        "Count"
    ]


    result["Percentage"] = (
        result["Count"]
        /
        result["Count"].sum()
        *
        100
    ).round(1)


    fig = px.bar(
        result,
        x="Category",
        y="Count",
        text=result.apply(
            lambda x:
            f'{x["Count"]}<br>{x["Percentage"]}%',
            axis=1
        ),
        color="Category",
        title="Amman-Berlin Declaration - Disability Inclusion Marker"
    )


    fig.update_layout(
        xaxis_title="Disability Inclusion Category",
        yaxis_title="Number of commitments"
    )


    fig.show()


    display(result)

excluded_sectors = [
    "72010",
    "72040",
    "73010"
]

data = data[
    ~data["Sector"]
    .astype(str)
    .isin(excluded_sectors)
]

interact(
    create_dashboard,

    Recipient=widgets.Dropdown(
        options=recipient_options,
        description="Recipient"
    ),

    Donor=widgets.Dropdown(
        options=donor_options,
        description="Donor"
    ),

    Sector=widgets.Dropdown(
        options=sector_options,
        description="Sector"
    )
);

!pip install streamlit -q

import streamlit as st
import pandas as pd
import plotly.express as px

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# 
# st.set_page_config(
#     page_title="Amman-Berlin Declaration",
#     layout="wide"
# )
# 
# 
# st.title("Amman-Berlin Declaration")
# 
# st.caption(
#     "OECD-DAC CRS analysis. Commitments only. "
#     "Each CRS record counted individually."
# )
# 
# 
# # -------------------------
# # Load data
# # -------------------------
# 
# @st.cache_data
# def load_data():
# 
#     df = pd.read_csv(
#         "oecd_data.csv",
#         encoding="latin1"
#     )
# 
#     return df
# 
# 
# df = load_data()
# 
# 
# # -------------------------
# # Apply filters
# # -------------------------
# 
# data = df.copy()
# 
# 
# # Only commitments
# 
# data = data[
#     data["FLOW_TYPE"]
#     .astype(str)
#     .str.upper()
#     .isin(["C", "COMMITMENT"])
# ]
# 
# 
# # Modalities
# 
# allowed_modalities = [
#     "A02",
#     "B01",
#     "B03",
#     "B04",
#     "C01",
#     "D01",
#     "D02",
#     "E01"
# ]
# 
# 
# data = data[
#     data["MODALITY"]
#     .astype(str)
#     .str[:3]
#     .isin(allowed_modalities)
# ]
# 
# 
# # Exclude sectors
# 
# excluded_sectors = [
#     "72010",
#     "72040",
#     "73010"
# ]
# 
# 
# data = data[
#     ~data["SECTOR"]
#     .astype(str)
#     .isin(excluded_sectors)
# ]
# 
# 
# # Disability classification
# 
# def disability_category(x):
# 
#     if pd.isna(x) or x == "":
#         return "Not scored"
# 
#     try:
#         x = int(x)
#     except:
#         return "Not scored"
# 
#     if x == 0:
#         return "Scored - not targeted"
# 
#     if x in [1,2]:
#         return "Targeted"
# 
#     return "Not scored"
# 
# 
# data["Disability Category"] = (
#     data["DISABILITY"]
#     .apply(disability_category)
# )
# 
# 
# # -------------------------
# # Sidebar filters
# # -------------------------
# 
# st.sidebar.header("Filters")
# 
# 
# recipient = st.sidebar.selectbox(
#     "Recipient",
#     ["All"] + sorted(
#         data["Recipient"]
#         .dropna()
#         .unique()
#         .tolist()
#     )
# )
# 
# 
# donor = st.sidebar.selectbox(
#     "Donor",
#     ["All"] + sorted(
#         data["Donor"]
#         .dropna()
#         .unique()
#         .tolist()
#     )
# )
# 
# 
# # Sector name column automatisch finden
# 
# if "Sector.1" in data.columns:
#     sector_name_col = "Sector.1"
# 
# elif "Sector" in data.columns:
#     sector_name_col = "Sector"
# 
# elif "Sector name" in data.columns:
#     sector_name_col = "Sector name"
# 
# else:
#     raise Exception(
#         "Keine Sector-Namensspalte gefunden. "
#         + str(data.columns.tolist())
#     )
# 
# 
# sector = st.sidebar.selectbox(
#     "Sector",
#     ["All"] + sorted(
#         data[sector_name_col]
#         .dropna()
#         .unique()
#         .tolist()
#     )
# )
# 
# 
# 
# filtered = data.copy()
# 
# 
# if recipient != "All":
#     filtered = filtered[
#         filtered["Recipient"] == recipient
#     ]
# 
# 
# if donor != "All":
#     filtered = filtered[
#         filtered["Donor"] == donor
#     ]
# 
# 
# if sector != "All":
#     filtered = filtered[
#         filtered[sector_name_col] == sector
#     ]
# 
# # -------------------------
# # Results
# # -------------------------
# 
# st.metric(
#     "Total CRS commitments analysed",
#     len(filtered)
# )
# 
# 
# result = (
#     filtered["Disability Category"]
#     .value_counts()
#     .reset_index()
# )
# 
# 
# result.columns = [
#     "Category",
#     "Count"
# ]
# 
# 
# result["Percentage"] = (
#     result["Count"]
#     /
#     result["Count"].sum()
#     *
#     100
# ).round(1)
# 
# 
# fig = px.bar(
#     result,
#     x="Category",
#     y="Count",
#     text=result.apply(
#         lambda x:
#         f'{x["Count"]}<br>{x["Percentage"]}%',
#         axis=1
#     ),
#     color="Category",
#     title="Disability Inclusion Marker"
# )
# 
# 
# st.plotly_chart(
#     fig,
#     use_container_width=True
# )
# 
# 
# st.dataframe(
#     result,
#     hide_index=True
# )
#

st.caption(
    "Source: OECD-DAC CRS. "
)

!streamlit run app.py &>/content/log.txt &

!streamlit run app.py &>/content/log.txt &

!pip install pyngrok -q

from pyngrok import ngrok

ngrok.set_auth_token("3GllmCLp24WrDinLtkd8NcVMuBD_WQD8kSTkbY55Mswt4Zip")

url = ngrok.connect(8501)

url